version: 0.0
os: linux
files:
  - source: caddy
    destination: /usr/local/bin/
  - source: info
    destination: /var/www/public/
permissions:
  - object: /var/www/public/info
    owner: www-data
    group: www-data
    mode: 0644
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root
